project_id = "ijlhgohhpefxbfswmwms"

[functions.chat]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.analyze-photo]
verify_jwt = true

[functions.create-test-partner]
verify_jwt = false

[functions.create-partner-account]
verify_jwt = true

[functions.create-test-partner-with-login]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false

[functions.save-chat-session]
verify_jwt = false

[functions.audit-logger]
verify_jwt = false

[functions.siem-export]
verify_jwt = false

[functions.get-yandex-maps-key]
verify_jwt = false
